 // Define contact data fields

 export const contactFields = (accountList, allIndustries, allUsers, allCountries, stateList, allContacts) =>[
  {
    title: 'First Name',
    name: 'firstName',
    type: 'text',
    placeholder: 'Enter first name',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
    maximumLength: 30,
  },
  {
    title: 'Last Name',
    name: 'lastName',
    type: 'text',
    placeholder: 'Enter last name',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
    maximumLength: 30,
  },
  {
    title: 'Referred By',
    name: 'referredBy',
    type: 'text',
    placeholder: 'Enter referral (optional)',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
    maximumLength: 30,
  },
  { title: 'Email', name: 'email', type: 'text', placeholder: 'Enter email' },
  {
    title: 'Designation',
    name: 'designation',
    type: 'text',
    placeholder: 'Enter designation',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
    maximumLength: 30,
  },
  {
    title: 'Apartment/House No.',
    name: 'contactAddress.apartment',
    type: 'text',
    placeholder: 'Enter apartment/house number',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
    maximumLength: 15,
  },
  {
    title: 'City',
    name: 'contactAddress.city',
    type: 'text',
    placeholder: 'Enter city name',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
    maximumLength: 20,
  },
  {
    title: 'Country',
    name: 'country',
    type: 'dropdown',
    options: allCountries?.map((countryList) => ({
      label: countryList.countryName,
      value: countryList._id,
    })),
    placeholder: 'Select a country',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
  },
  {
    title: 'State',
    name: 'state',
    type: 'dropdown',
    options: stateList?.map((state) => ({
      label: state.stateName,
      value: state._id,
    })),
    placeholder: 'Select a state',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
  },
  {
    title: 'Postal Code',
    name: 'contactAddress.postalCode',
    type: 'text',
    keyfilter:'int',
    placeholder: 'Enter postal code',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
    maximumLength: 6,
  },
  {
    title: 'Industry',
    name: 'industry',
    type: 'dropdown',
    options: allIndustries?.map((industry) => ({
      label: industry.name,
      value: industry._id,
    })),
    placeholder: 'Select an industry',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
  },
  {
    title: 'Company Name / Account',
    name: 'accountOrg',
    type: 'dropdown',
    options: accountList?.map?.((account) => ({
      label: account.title,
      value: account._id,
    })),
    placeholder: 'Select an account',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
  },
  {
    title: 'LinkedIn URL',
    name: 'linkedInUrl',
    type: 'text',
    placeholder: 'Enter LinkedIn URL',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
  },
  {
    title: 'Business Unit',
    name: 'businessUnit',
    type: 'text',
    placeholder: 'Enter a business unit',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
    maximumLength: 30,
  },
  {
    title: 'Assign To',
    name: 'assignTo',
    type: 'dropdown',
    options: allUsers?.map((user) => ({
      label: user.fullName,
      value: user._id,
    })),
    placeholder: 'Assign to',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
  },
  {
    title: 'Reporting To',
    name: 'reportingTo',
    type: 'dropdown',
    options: allContacts?.map((contact) => ({
      label: contact.firstName,
      value: contact._id,
    })),
    placeholder: 'Select reporting manager',
    parentClassName: 'col-12 md:col-4 lg:col-4',
    className: 'w-full',
  }
];
