name: DO Build and publish manually
on:
  push:
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: archive
        run: |
          npm install
          npm run build
          zip -r build.zip .
      - run: npm ci   
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: build.zip
          host: talency.co
          remote: .
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: talency.co
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
